version: "3"

services:
  mongo:
    image: mongo
    restart: "always"
    volumes:
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27015:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app

  node:
    image: node:lts-slim
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "yarn dev"
    networks:
      - app

networks:
  app:
    driver: "bridge"
